### ISSUE TITLE
根据 readme 文档执行 main.py 时报错

### ISSUE THREAD

**Issue by jianghao-chen** [longbridgeapp/openapi-python#4]
根据 readme 文档已经安装了 longbridge、protobuf 模块，但是在运行 main.py 时仍报以下错误，是否还需要安装其它模块？

/usr/local/anaconda3/envs/openapi-python-main/bin/python /Users/hkfdt/work/python_workspac/openapi-python-main/main.py
Traceback (most recent call last):
  File "/Users/hkfdt/work/python_workspac/openapi-python-main/main.py", line 3, in <module>
    from longbridge.http import Auth, Config, HttpClient
  File "/Users/hkfdt/work/python_workspac/openapi-python-main/longbridge/__init__.py", line 1, in <module>
    from . import engine_uniffi
  File "/Users/hkfdt/work/python_workspac/openapi-python-main/longbridge/engine_uniffi.py", line 344, in <module>
    _UniFFILib = loadIndirect()
  File "/Users/hkfdt/work/python_workspac/openapi-python-main/longbridge/engine_uniffi.py", line 339, in loadIndirect
    return ctypes.cdll.LoadLibrary(path)
  File "/usr/local/anaconda3/envs/openapi-python-main/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/anaconda3/envs/openapi-python-main/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/hkfdt/work/python_workspac/openapi-python-main/longbridge/libengine_uniffi.dylib, 0x0006): tried: '/Users/hkfdt/work/python_workspac/openapi-python-main/longbridge/libengine_uniffi.dylib' (no such file), '/usr/local/lib/libengine_uniffi.dylib' (no such file), '/usr/lib/libengine_uniffi.dylib' (no such file)

Process finished with exit code 1

**Comment by flisky** [comment]
确认下 ‘/Users/hkfdt/work/python_workspac/openapi-python-main/longbridge/libengine_uniffi.dylib’ 这个文件是否存在。如果不存在，请重新安装。

**Comment by terryleetracymc** [comment]
libengine_uniffi是通过什么安装的？

> 确认下 ‘/Users/hkfdt/work/python_workspac/openapi-python-main/longbridge/libengine_uniffi.dylib’ 这个文件是否存在。如果不存在，请重新安装。
